### ISSUE TITLE
HttpbinRequest-sources.jar没添加吗

### ISSUE THREAD

**Issue by mundane799699** [xxxzhi/RetrofitDemo#1]

**Comment by xxxzhi** [comment]
你是指这个文件[HttpbinRequest](https://github.com/xxxzhi/RetrofitDemo/blob/master/app/src/main/java/com/houzhi/retrofitdemo/model/HttpbinRequest.java)?

不需要jar包.

**Comment by mundane799699** [comment]
但是你看app下面gradle文件里dependencies里第二行,  明明有compile files('libs/HttpbinRequest-sources.jar')这么一句.  我把这句去掉也能运行?

**Comment by xxxzhi** [comment]
哦，谢谢，去掉没关系的，我这留在里面也能够编译。忘了怎么搞进去的。我去掉了重新提交了一下。

**Comment by mundane799699** [comment]
好
